### ISSUE TITLE
Certificate and Key file

### ISSUE THREAD

**Issue by sgabb** [grafana/django-saml2-auth#25] opened 2022-03-09 16:03 UTC
Hello!
Is it there a way to specify certificate and key file or information?
Something like it is done within pysaml2:
https://pysaml2.readthedocs.io/en/latest/howto/config.html#cert-file

At the moment when the code execute **saml_client = Saml2Client(config=sp_config)**:
https://github.com/grafana/django-saml2-auth/blob/46181c19e53cc9949767ce851ba8fa7696b71266/django_saml2_auth/saml.py#L197

then runs here:
https://github.com/IdentityPython/pysaml2/blob/155910dabffa0f60a2075be862f2cf8c31fad685/src/saml2/sigver.py#L1044

doesn't find the file and return sec_backend = None

Then, here gives error because of the above:
https://github.com/IdentityPython/pysaml2/blob/master/src/saml2/pack.py#L194

Any advice?
Thank you very much.

**Comment by mostafa** [comment] 2022-03-10 11:26
Hey @sgabb,

Can you explain what you're trying to do with the certificate and the key file? AFAIK, the certificate is already available in the metadata file and the library automatically picks it up and signs assertions with it.

**Comment by mostafa** [comment] 2022-03-10 18:01
It seems like there's a configuration issue of sorts with your code because the certificate should be extracted from the metadata file. Are you setting the `METADATA_LOCAL_FILE_PATH` option and the path is accessible from your Django app? You also need to set `WANT_ASSERTIONS_SIGNED` and `WANT_RESPONSE_SIGNED` to `True`.

**Comment by sgabb** [comment] 2022-03-10 19:23
This are my settings:
```py
SAML2_AUTH = {
    # Metadata is required, choose either remote url or local file path
    'METADATA_LOCAL_FILE_PATH': os.path.join(BASE_DIR, "web", "settings", "metadata.xml"),
    'DEBUG': True,

    # Optional settings below
    'DEFAULT_NEXT_URL': '/',
    'ATTRIBUTES_MAP': {
        'first_name': 'Given Name',
        'last_name': 'Surname',
        'email': 'Email',
        'username': 'Email',
    },
    'WANT_ASSERTIONS_SIGNED': True,
    'AUTHN_REQUESTS_SIGNED': True,
    'WANT_RESPONSE_SIGNED': True,
    # Set 'USE_JWT' to True if you are running a Single Page Application (SPA) with Django Rest Framework (DRF),
    # and are using JWT authentication to authorize client users
    'USE_JWT': True,
    # Redirect URL for the client if you are using JWT auth with DRF. See explanation below
    'FRONTEND_URL': 'http://frontend.domain/sso/login',
}
```
And this is the resulting saml_settings prepared in [get_saml_client](https://github.com/grafana/django-saml2-auth/blob/master/django_saml2_auth/saml.py#L152):
```yaml
{'metadata': {'local': ['/app/web/settings/metadata.xml']}, 'allow_unknown_attributes': True, 'debug': True, 'service': {'sp': {'endpoints': {'assertion_consumer_service': [('http://localhost:8000/saml/acs/', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'), ('http://localhost:8000/saml/acs/', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST')]}, 'allow_unsolicited': True, 'authn_requests_signed': True, 'logout_requests_signed': True, 'want_assertions_signed': True, 'want_response_signed': True}}}
```

Trying to set in settings WANT_ASSERTIONS_SIGNED, AUTHN_REQUESTS_SIGNED and WANT_RESPONSE_SIGNED to False, it creates the AuthNReq and does the redirect.
This is the AuthNReq printed:
```xml
<ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" ID="id-requestuid" Version="2.0" IssueInstant="2022-03-10T19:10:50Z" Destination="https://login.microsoftonline.com/uuid/saml2" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="http://localhost:8000/saml/login/"><ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" /></ns0:AuthnRequest>
```
However the microsoft login page gives an error:
Request Id: uuid1
Correlation Id: uuid2
Timestamp: 2022-03-10T19:10:51Z
Message: **AADSTS7500525: There was an XML error in the SAML message at line 1, position 488. Verify that the XML content of the SAML messages conforms to the SAML protocol specifications.**

where line 488 is right before "ns0:AuthnRequest>".

**Comment by mostafa** [comment] 2022-03-11 11:38
Based on [these tests](https://github.com/grafana/django-saml2-auth/blob/master/django_saml2_auth/tests/test_saml.py#L266-L288), it should work fine unless there's a misconfiguration somewhere. I suggest you follow [this guide](https://k6.io/docs/cloud/project-and-team-management/saml-sso/azure-ad/), specifically step 13, as it might help pinpoint configuration issues on your SAML app (on Azure). You can also make use of SAML-tracer addon for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/) or [Chrome](https://chrome.google.com/webstore/detail/saml-tracer/mpdajninpobndbfcldcmbpnnbhibjmch?hl=en) to debug SAML messages.

**Comment by mostafa** [comment] 2022-03-16 15:56
@sgabb Nice find!
Also, if the authentication requests are not signed, it means you haven't installed `xmlsec1` on your system. If so, then there's some other configuration issue somewhere.

**Comment by sgabb** [comment] 2022-03-25 18:32
Unfortunately not yet :disappointed: 
Could it be linked to [this issue](https://github.com/fangli/django-saml2-auth/issues/48) of the original fangli repository?

This is an example of the metadata where there should be the Key and Certificate:
<details><summary>XML METADATA</summary>
<p>

```xml
<?xml version="1.0" encoding="utf-8"?>
<EntityDescriptor ID="entity-descriptor-id" entityID="https://sts.windows.net/entity-id/" xmlns="urn:oasis:names:tc:SAML:2.0:metadata">
    <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
        <SignedInfo>
            <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
            <Reference URI="#entity-descriptor-id">
                <Transforms>
                    <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                </Transforms>
                <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                <DigestValue>b6libAlGkhZQK7d97/2sxahiOxxAsae58Uho5RHr8aI=</DigestValue>
            </Reference>
        </SignedInfo>
        <SignatureValue>signature-value-uid</SignatureValue>
        <KeyInfo>
            <X509Data>
                <X509Certificate>x509-certificate-string</X509Certificate>
            </X509Data>
        </KeyInfo>
    </Signature>
    <RoleDescriptor xsi:type="fed:SecurityTokenServiceType" protocolSupportEnumeration="http://docs.oasis-open.org/wsfed/federation/200706" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fed="http://docs.oasis-open.org/wsfed/federation/200706">
        <KeyDescriptor use="signing">
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <X509Data>
                    <X509Certificate>x509-certificate-string</X509Certificate>
                </X509Data>
            </KeyInfo>
        </KeyDescriptor>
        <fed:ClaimTypesOffered>
            <auth:ClaimType Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Name</auth:DisplayName>
                <auth:Description>The mutable display name of the user.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Subject</auth:DisplayName>
                <auth:Description>An immutable, globally unique, non-reusable identifier of the user that is unique to the application for which a token is issued.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Given Name</auth:DisplayName>
                <auth:Description>First name of the user.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Surname</auth:DisplayName>
                <auth:Description>Last name of the user.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/displayname" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Display Name</auth:DisplayName>
                <auth:Description>Display name of the user.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/nickname" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Nick Name</auth:DisplayName>
                <auth:Description>Nick name of the user.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Authentication Instant</auth:DisplayName>
                <auth:Description>The time (UTC) when the user is authenticated to Windows Azure Active Directory.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Authentication Method</auth:DisplayName>
                <auth:Description>The method that Windows Azure Active Directory uses to authenticate users.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/objectidentifier" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>ObjectIdentifier</auth:DisplayName>
                <auth:Description>Primary identifier for the user in the directory. Immutable, globally unique, non-reusable.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/tenantid" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>TenantId</auth:DisplayName>
                <auth:Description>Identifier for the user's tenant.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/identityprovider" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>IdentityProvider</auth:DisplayName>
                <auth:Description>Identity provider for the user.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Email</auth:DisplayName>
                <auth:Description>Email address of the user.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/groups" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Groups</auth:DisplayName>
                <auth:Description>Groups of the user.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/accesstoken" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>External Access Token</auth:DisplayName>
                <auth:Description>Access token issued by external identity provider.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/expiration" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>External Access Token Expiration</auth:DisplayName>
                <auth:Description>UTC expiration time of access token issued by external identity provider.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/identity/claims/openid2_id" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>External OpenID 2.0 Identifier</auth:DisplayName>
                <auth:Description>OpenID 2.0 identifier issued by external identity provider.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/claims/groups.link" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>GroupsOverageClaim</auth:DisplayName>
                <auth:Description>Issued when number of user's group claims exceeds return limit.</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/role" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>Role Claim</auth:DisplayName>
                <auth:Description>Roles that the user or Service Principal is attached to</auth:Description>
            </auth:ClaimType>
            <auth:ClaimType Uri="http://schemas.microsoft.com/ws/2008/06/identity/claims/wids" xmlns:auth="http://docs.oasis-open.org/wsfed/authorization/200706">
                <auth:DisplayName>RoleTemplate Id Claim</auth:DisplayName>
                <auth:Description>Role template id of the Built-in Directory Roles that the user is a member of</auth:Description>
            </auth:ClaimType>
        </fed:ClaimTypesOffered>
        <fed:SecurityTokenServiceEndpoint>
            <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                <wsa:Address>https://login.microsoftonline.com/entity-id/wsfed</wsa:Address>
            </wsa:EndpointReference>
        </fed:SecurityTokenServiceEndpoint>
        <fed:PassiveRequestorEndpoint>
            <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                <wsa:Address>https://login.microsoftonline.com/entity-id/wsfed</wsa:Address>
            </wsa:EndpointReference>
        </fed:PassiveRequestorEndpoint>
    </RoleDescriptor>
    <RoleDescriptor xsi:type="fed:ApplicationServiceType" protocolSupportEnumeration="http://docs.oasis-open.org/wsfed/federation/200706" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fed="http://docs.oasis-open.org/wsfed/federation/200706">
        <KeyDescriptor use="signing">
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <X509Data>
                    <X509Certificate>x509-certificate-string</X509Certificate>
                </X509Data>
            </KeyInfo>
        </KeyDescriptor>
        <fed:TargetScopes>
            <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                <wsa:Address>https://sts.windows.net/entity-id/</wsa:Address>
            </wsa:EndpointReference>
        </fed:TargetScopes>
        <fed:ApplicationServiceEndpoint>
            <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                <wsa:Address>https://login.microsoftonline.com/entity-id/wsfed</wsa:Address>
            </wsa:EndpointReference>
        </fed:ApplicationServiceEndpoint>
        <fed:PassiveRequestorEndpoint>
            <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                <wsa:Address>https://login.microsoftonline.com/entity-id/wsfed</wsa:Address>
            </wsa:EndpointReference>
        </fed:PassiveRequestorEndpoint>
    </RoleDescriptor>
    <IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <KeyDescriptor use="signing">
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <X509Data>
                    <X509Certificate>x509-certificate-string</X509Certificate>
                </X509Data>
            </KeyInfo>
        </KeyDescriptor>
        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://login.microsoftonline.com/entity-id/saml2" />
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://login.microsoftonline.com/entity-id/saml2" />
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://login.microsoftonline.com/entity-id/saml2" />
    </IDPSSODescriptor>
</EntityDescriptor>
```
</p>
</details>

Does it look correct? Should the library read the private key and the certificate value from it without issue?
I am still not sure if the issue regards the configuration of the metadata or if the library effectively does not search within the metadata but need to receive the key_file and cert_file as requested in pysam2...

**Comment by mostafa** [comment] 2022-03-29 09:15
@sgabb 
It all seems like a configuration issue to me. Have you read https://github.com/IdentityPython/pysaml2/issues/598?

**Comment by rhelms** [comment] 2022-06-15 02:20
I'm running into this issue as well.

I'm very early days into doing my development, so I'm using https://samltest.id/saml/idp as the IdP to authenticate against. I'm assuming that this should be the value of METADATA_AUTO_CONF_URL.

If I set AUTHN_REQUESTS_SIGNED to False, I'm able to trigger a SP initiated request and get the redirect to the IdP.

However, if AUTHN_REQUESTS_SIGNED is True, then I end up with an exception from the bowels of the saml2 lib.

Here is a stack trace of where the error is coming from.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django_saml2_auth/utils.py", line 165, in wrapper
    result = function(request)
  File "/usr/local/lib/python3.7/dist-packages/django_saml2_auth/views.py", line 267, in signin
    _, info = saml_client.prepare_for_authenticate(relay_state=next_url)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/saml2/client.py", line 84, in prepare_for_authenticate
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/saml2/client.py", line 168, in prepare_for_negotiated_authenticate
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/saml2/client_base.py", line 494, in create_authn_request
    **args,
  File "/usr/local/lib/python3.7/dist-packages/saml2/entity.py", line 610, in _message
    digest_alg=digest_alg,
  File "/usr/local/lib/python3.7/dist-packages/saml2/entity.py", line 542, in sign
    return signed_instance_factory(msg, self.sec, to_sign)
  File "/usr/local/lib/python3.7/dist-packages/saml2/sigver.py", line 345, in signed_instance_factory
    signed_xml, node_name=node_name, node_id=nodeid
  File "/usr/local/lib/python3.7/dist-packages/saml2/sigver.py", line 1790, in sign_statement
    node_id,
  File "/usr/local/lib/python3.7/dist-packages/saml2/sigver.py", line 860, in sign_statement
    (stdout, stderr, output) = self._run_xmlsec(com_list, [tmp.name])
  File "/usr/local/lib/python3.7/dist-packages/saml2/sigver.py", line 921, in _run_xmlsec
    logger.debug('xmlsec command: %s', ' '.join(com_list))
TypeError: sequence item 3: expected str instance, NoneType found
```

From what I can make out, item 3 is a key_file, either put to disk by saml2 or passed as an actual file location.

However, I can't find the location in the code that would extract a signing key file from either my own metadata (wouldn't that be dangerous?) or the IdP metadata. From all that I've seen, it would appear they a key_file attribute is expected in the saml_settings provided in django_saml2_auth/saml.py.

**Comment by tdiaque** [comment] 2022-07-26 14:53
Do we know if this issue is being looked into? I am also running into this issue after 8hrs of troubleshooting with no luck between django_saml2_auth and saml2.client.py I was able to see that the issue is somewhere with samlclient and I am getting the exception: **TypeError: sequence item 3: expected str instance, NoneType found** as well

**Comment by defigor** [comment] 2022-10-31 05:22
Any updates on the issue? We have the same issue. We tried locally to test Google IdP with this library on both Windows/Linux (CentOS) machines.
As per other comments we are getting **TypeError: sequence item 3: expected str instance, NoneType found** error where it seems that the library passes **None** as the private cert file location to xmlsec and hence it fails.
If we disable following settings as per code below:
`    'WANT_ASSERTIONS_SIGNED': False,
    'AUTHN_REQUESTS_SIGNED': False,
    'WANT_RESPONSE_SIGNED': False,
`
We get the redirect to Google, however upon selecting the user, we get another exception: **failed to verify signature**.
Would appreciate any help. Happy to do further testing and provide any required information.

**Comment by michaelsteigman** [comment] 2022-11-08 19:45
> Any updates on the issue? We have the same issue. We tried locally to test Google IdP with this library on both Windows/Linux (CentOS) machines.
> As per other comments we are getting **TypeError: sequence item 3: expected str instance, NoneType found** error where it seems that the library passes **None** as the private cert file location to xmlsec and hence it fails.
> If we disable following settings as per code below:
> ` 'WANT_ASSERTIONS_SIGNED': False, 'AUTHN_REQUESTS_SIGNED': False, 'WANT_RESPONSE_SIGNED': False,`
> We get the redirect to Google, however upon selecting the user, we get another exception: **failed to verify signature**.
> Would appreciate any help. Happy to do further testing and provide any required information.

Exact same situation here. Django 4.1, Python 3.8 and Okta dev tennant.

**Comment by mostafa** [comment] 2022-11-14 09:21
@michaelsteigman @defigor @tdiaque @rhelms 
AFAIK, if the key is not present in the metadata file, currently there's no way to explicitly pass it as part of the configuration settings. Can you confirm that the key is present in the metadata file? This is what @sgabb also figured out from [an issue](https://github.com/grafana/django-saml2-auth/issues/25#issuecomment-1079296043) on fangli repo. I'll try to see if I can fix it. 👀

**Comment by michaelsteigman** [comment] 2022-11-14 17:27
@mostafa There is a request signing cert in the Okta metadata.

```
<md:EntityDescriptor entityID="http://www.okta.com/..">
<md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<md:KeyDescriptor use="signing">
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
...
```

Seems like this is what we're looking for?

**Comment by defigor** [comment] 2022-11-14 23:24
@mostafa 
The same here, this is how it looks in the Google metadata:
`
<?xml version="1.0" encoding="UTF-8"?><md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://accounts.google.com/o/saml2?idpid=ID_GOES_HERE" validUntil="SOME_TIME_GOES_HERE">
  <md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <md:KeyDescriptor use="signing">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>CERTIFICATE_HERE</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
    <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://accounts.google.com/o/saml2/idp?idpid=ID_GOES_HERE"/>
    <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://accounts.google.com/o/saml2/idp?idpid=ID_GOES_HERE"/>
  </md:IDPSSODescriptor>
</md:EntityDescriptor>
`

We wanted to use this library, but couldn't wait that long for this :( We've already switched to djangosaml2 ( https://github.com/IdentityPython/djangosaml2 ) instead and it works with no issues.

**Comment by mostafa** [comment] 2022-11-15 08:39
@defigor Are you passing your own certificate or is it auto-generated?

**Comment by defigor** [comment] 2022-11-15 08:47
@mostafa what do you mean passing? I was passing the metadata file via METADATA_LOCAL_FILE_PATH, that contained the certificate. This certificate is generated by Google when you setup a custom SAML app (but it seems that this certificate is being reused across all SAML apps in google).

See these links for more details:
https://support.google.com/a/answer/6087519?product_name=UnuFlow&hl=en&visit_id=638040987359057980-994443535&rd=1&src=supportwidget0&hl=en
https://support.google.com/a/answer/7394709?product_name=UnuFlow&hl=en&visit_id=638040987359057980-994443535&rd=1&src=supportwidget0&hl=en

**Comment by utaladriz** [comment] 2022-12-29 23:52
Same error.  TypeError: sequence item 3: expected str instance, NoneType found error. I trace the library and passes None as the private cert file location to xmlsec and hence it fails.

**Comment by rmincling** [comment] 2023-03-23 11:57
I get the same error "TypeError: sequence item 3: expected str instance, NoneType found error" as well. Has there been any progress with this?

**Comment by utaladriz** [comment] 2023-03-23 12:03
we switched to djangosaml2

**Comment by defigor** [comment] 2023-06-04 20:38
We also switched to djangosaml2 because could not get this one to work :(

**Comment by stephy-joseph** [comment] 2023-06-12 08:39
> ```python
>     'USE_JWT': True,
> ```

I am also facing the same issue ..my request is not getting signed from the SP....can you help me .

Below is my saml configuration
AML_CONFIG = {
    'xmlsec_binary': '/usr/bin/xmlsec1',
    'name': 'authentik',
    'entityid': 'http://localhost:8003/saml2/metadata/',
    'service': {
        'sp': {
            'want_assertions_signed': True,
            'want_response_signed': True,
            'allow_unsolicited': True,
            'endpoints': {
                'assertion_consumer_service': [
                    ('http://localhost:8003/saml/acs/', saml2.BINDING_HTTP_POST),
                ],
                'single_logout_service': [
                    ('http://localhost:8003/saml/ls/', saml2.BINDING_HTTP_REDIRECT),
                ],
            },
            'required_attributes': ['email'],
            'assertionConsumerService': {
                'url': 'localhost:8003/admins/message/',  # URL to receive SAML responses
                # Use the Redirect binding
                'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            },
        },
    },
    'debug': 1,
    'key_file': os.path.join(BASE_DIR, 'authentik_private_key.pem'),
    'cert_file': os.path.join(BASE_DIR, 'authentik_certificate.pem'),
    'allow_unknown_attributes': True,
    'metadata': {
        'local': [os.path.join(BASE_DIR, 'SAML-admin_authentik_meta.xml')],
    },
    'valid_for': 24,  # how long is our metadata valid
    'accepted_time_diff': 120,  # seconds
}

**Comment by sgabb** [comment] 2023-06-16 15:40
I've done a quick check on the code and it seemed quite easy to add a configuration to add the key and cert file and pass them down to pysaml2 library.
I've made a PR that @mostafa may check https://github.com/grafana/django-saml2-auth/pull/176

If anybody that has "working" configuration that were broken because of the missing files, maybe can try checking the fork and test it to see if it works.
I haven't had the time to add specific tests, but there weren't already as it seems for checking signed requests and responses...if someone can try it out then it's already a good starting point :grin:

**Comment by mostafa** [comment] 2023-07-04 10:34
@sgabb 

Thanks for your contribution! I just merged it.

**Comment by sgabb** [comment] 2023-07-04 11:04
@mostafa my pleasure!
Sorry about adding additional tests but I was a bit busy.
However I tested it on a real working environment and it kinda worked! The AuthRequest was created with the certificate correctly (SP initiated request), than there was an error on the IdP but it was probably a misconfiguration on their part.

I am not sure what type of test we could prepare, maybe just trying the creation of a request by setting `AUTHN_REQUESTS_SIGNED=True`, but at least now it doesn't break :muscle:

**Comment by mostafa** [comment] 2023-07-04 11:12
@sgabb 
Are you confident in the code and tests and should I go forward with the release or it needs more testings? I can think of a few options for testing:
1. A developer account on Okta: easier to set up and test and we can store credentials and keys on GitHub.
2. A local IdP for testing in CI: needs more investigation and possibly harder to configure, but is not prone to any attack vectors (I know of).

WDYT?

**Comment by sgabb** [comment] 2023-07-04 11:31
I am confident because the addition is very small and only add the possibility to pass down to pysaml the key and cert files. I would go forward with the release, and then we can think of adding some testing for signed requests and responses.

For sure it is better than before because it was immediately breaking whenever the settings asked for signing.

**Comment by jonprindiville** [comment] 2023-07-04 21:07
For context: I'm also integrating a Django site with Okta SSO, and am currently in the middle of switching from the fangli/django-saml2-auth to this one.

I had been hitting that `TypeError: sequence item 3: expected str instance, NoneType found` issue, and now I am not.

The fix for me was to set `AUTHN_REQUESTS_SIGNED` to `False`.

When I go looking for Okta docs on the subject I notice that they explicitly mention they will always have `WantAuthnRequestsSigned="false"` in the metadata and they don't sign AuthN requests:
    https://support.okta.com/help/s/article/Can-the-WantAuthnRequestsSigned-value-be-set-to-True?language=en_US

(I also notice that in the fangli/django-saml2-auth there is no config for it, but it had been passing `authn_requests_signed=False` into the underlying SAML libraries.)

I didn't change the default `WANT_ASSERTIONS_SIGNED=True` or the default `WANT_RESPONSE_SIGNED=True` -- those seem fine as is for me.

---

@michaelsteigman 

> There is a request signing cert in the Okta metadata.

Yes, but there is also a `WantAuthnRequestsSigned="false"` in there.

@defigor IDK anything about the Google service specifically, I'm using Okta, but I see `WantAuthnRequestsSigned="false"` in your metadata, too. Maybe Google support/docs can give more context?

**Comment by sgabb** [comment] 2023-07-05 14:12
@jonprindiville setting `AUTHN_REQUESTS_SIGNED=False` works because it does not try to use the key and cert files.
If Okta does not want the request signed then it is ok, however for anyone that want it signed the files needs to be passed.

Now it is possible to set the request signed and shouldn't give the previous TypeError.

**Comment by jonprindiville** [comment] 2023-07-05 20:38
> Now it is possible to set the request signed and shouldn't give the previous TypeError.

I saw -- nice addition 👍

> If Okta does not want the request signed then it is ok, however for anyone that want it signed the files needs to be passed.

Yep, totally.

I just wanted to note **for other Okta-using folk** in this thread who might be tripping over the AuthN signing that it seems like supplying a cert and key is probably barking up the wrong tree based on [that Okta support doc](https://support.okta.com/help/s/article/Can-the-WantAuthnRequestsSigned-value-be-set-to-True)

**Comment by mostafa** [comment] 2023-07-31 09:41
Hey @sgabb and everyone else tracking this issue,

I just released [v3.11.0](https://github.com/grafana/django-saml2-auth/releases/tag/v3.11.0).

**Closed by mostafa** 2023-07-31 09:41 UTC
Labels: awaiting-feedback

**Comment by kartzman** [comment] 2023-09-27 18:31
Hi. I updated to 3.11 and I'm still getting the same error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django_saml2_auth/utils.py", line 185, in wrapper
    result = function(request)
  File "/usr/local/lib/python3.9/dist-packages/django_saml2_auth/views.py", line 276, in signin
    _, info = saml_client.prepare_for_authenticate(relay_state=next_url)  # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/saml2/client.py", line 72, in prepare_for_authenticate
    reqid, negotiated_binding, info = self.prepare_for_negotiated_authenticate(
  File "/usr/local/lib/python3.9/dist-packages/saml2/client.py", line 150, in prepare_for_negotiated_authenticate
    reqid, request = self.create_authn_request(
  File "/usr/local/lib/python3.9/dist-packages/saml2/client_base.py", line 446, in create_authn_request
    msg = self._message(
  File "/usr/local/lib/python3.9/dist-packages/saml2/entity.py", line 588, in _message
    signed_req = self.sign(
  File "/usr/local/lib/python3.9/dist-packages/saml2/entity.py", line 524, in sign
    return signed_instance_factory(msg, self.sec, to_sign)
  File "/usr/local/lib/python3.9/dist-packages/saml2/sigver.py", line 331, in signed_instance_factory
    signed_xml = seccont.sign_statement(signed_xml, node_name=node_name, node_id=nodeid)
  File "/usr/local/lib/python3.9/dist-packages/saml2/sigver.py", line 1673, in sign_statement
    return self.crypto.sign_statement(
  File "/usr/local/lib/python3.9/dist-packages/saml2/sigver.py", line 779, in sign_statement
    (stdout, stderr, output) = self._run_xmlsec(com_list, [tmp.name])
  File "/usr/local/lib/python3.9/dist-packages/saml2/sigver.py", line 841, in _run_xmlsec
    logger.debug("xmlsec command: %s", " ".join(com_list))
TypeError: sequence item 3: expected str instance, NoneType found

Internal Server Error: /mailman3/accounts/login/

**Comment by mostafa** [comment] 2023-09-28 21:31
@kartzman Let's follow up in the other ticket: https://github.com/grafana/django-saml2-auth/issues/207#issuecomment-1740030983
